# Generated by Django 2.1.7 on 2019-09-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('crime_status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('PENDING', 'PENDING')], default='OPEN', max_length=50)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('verdict', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_location', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_crime', models.DateField(blank=True, null=True)),
                ('time_of_crime', models.TimeField(blank=True, null=True)),
                ('statement', models.CharField(blank=True, max_length=255, null=True)),
                ('added_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('aliases', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('hair_color', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('wanted_status', models.CharField(choices=[('WANTED', 'wanted'), ('NOT_WANTED', 'not_wanted')], default='NOT_WANTED', max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('foot_size', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_arrest', models.CharField(blank=True, max_length=255, null=True)),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_arrest', models.DateField(blank=True, null=True)),
                ('crime', models.ManyToManyField(to='Criminal.Crime')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='default1.jpg', upload_to='criminal_pics/')),
                ('image2', models.ImageField(default='default2.jpg', upload_to='criminal_pics/')),
                ('criminal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Criminal.Criminal')),
            ],
        ),
        migrations.CreateModel(
            name='FingerPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_thumb', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('right_index', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('right_middle', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('right_ring', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('right_pinky', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('left_thumb', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('left_index', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('left_middle', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('left_ring', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('left_pinky', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
            ],
        ),
    ]
