# Generated by Django 2.1.7 on 2019-10-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminal', '0002_crime_police'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalimage',
            name='criminal',
        ),
        migrations.AddField(
            model_name='criminal',
            name='image1',
            field=models.ImageField(default='default1.jpg', upload_to='criminal_pics/'),
        ),
        migrations.AddField(
            model_name='criminal',
            name='image2',
            field=models.ImageField(default='default2.jpg', upload_to='criminal_pics/'),
        ),
        migrations.DeleteModel(
            name='CriminalImage',
        ),
    ]
