# Generated by Django 2.1.7 on 2019-10-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminal', '0003_auto_20191010_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='crime_location',
            new_name='city_of_crime',
        ),
        migrations.AddField(
            model_name='crime',
            name='country_of_crime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='state_of_crime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
