# Generated by Django 2.1.7 on 2019-12-16 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminal', '0003_auto_20191216_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 22, 31, 50, 153070)),
        ),
    ]
