# Generated by Django 2.1.7 on 2019-10-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminal', '0005_auto_20191014_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
