# Generated by Django 2.1.7 on 2019-12-28 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminal', '0005_auto_20191216_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 11, 31, 53, 635831)),
        ),
    ]
