# Generated by Django 2.1.7 on 2019-10-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminal', '0006_auto_20191014_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
