# Generated by Django 2.1.7 on 2020-01-08 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminal', '0007_auto_20200108_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 16, 43, 16, 624492)),
        ),
    ]
