# Generated by Django 2.2.7 on 2020-02-06 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Criminal', '0008_auto_20200108_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 20, 34, 7, 985002)),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='description',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
